//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHARCAMA
    {
        public int HARCAMAID { get; set; }
        public int MUSTERIID { get; set; }
        public Nullable<decimal> HARCAMATUTAR { get; set; }
        public Nullable<System.DateTime> HARCAMATARIH { get; set; }
    
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
    }
}
