//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERI()
        {
            this.TBLHARCAMA = new HashSet<TBLHARCAMA>();
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
        }
    
        public int MUSTERIID { get; set; }
        [Required(ErrorMessage ="Müþteri Adý Boþ Geçilemez!")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakter Girebilirsiniz")]
        public string MUSTERIAD { get; set; }
        public string MUSTERSOYAD { get; set; }
        public string MUSTERISEHIR { get; set; }
        public Nullable<decimal> MUSTERIBAKIYE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHARCAMA> TBLHARCAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
    }
}
